version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:current
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save cache
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Inject Firebase configuration into environments.ts
          command: |
            mkdir -p src/environments
            echo ${ENV_FILE} > src/environments/environment.ts
      - run:
          name: Build project
          command: npm run build --prod
      - run:
          name: Make keys file
          command: echo ${TIME_KEYS} > keys.json
      - run:
          name: Deploy to Firebase Hosting
          command: |
            sudo npm install -g firebase-tools
            firebase deploy --only hosting
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: "keys.json"


workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
